### ISSUE TITLE
Build les images de manière spécifique

### ISSUE THREAD

**Issue by RemiSaurel** [memoire-app/memoire-deploy#11]
On peut ajouter des conditions sur les fichiers via les GH actions : 

```
on:
  push:
    paths:
      - folder1/**
```
